// Misc. initializations
OUTER_SPRINT ui_scrollbar ~GUISCRC~   // list scrollbar BAM resref
OUTER_SPRINT ui_vars_area_list ~cheatAreaDisplayList~ // area table name
OUTER_SPRINT ui_vars_area_strref ~false~  // whether area description is stored as strref

// Determine game mode
ACTION_IF (GAME_IS ~eet~) BEGIN
  OUTER_SPRINT game ~eet~
  OUTER_SPRINT ui_mode ~bg2ee~
END ELSE ACTION_IF (GAME_IS ~bgee~) BEGIN
  ACTION_IF (GAME_INCLUDES ~sod~) BEGIN
    OUTER_SPRINT game ~sod~
    OUTER_SPRINT ui_mode ~sod~
  END ELSE BEGIN
    OUTER_SPRINT game ~bgee~
    OUTER_SPRINT ui_mode ~bgee~
  END
END ELSE ACTION_IF (GAME_IS ~bg2ee~) BEGIN
  OUTER_SPRINT game ~bg2ee~
  OUTER_SPRINT ui_mode ~bg2ee~
END ELSE ACTION_IF (GAME_IS ~iwdee~) BEGIN
  OUTER_SPRINT game ~iwdee~
  OUTER_SPRINT ui_mode ~iwdee~
END ELSE ACTION_IF (GAME_IS ~pstee~) BEGIN
  OUTER_SPRINT game ~pstee~
  OUTER_SPRINT ui_mode ~pstee~
  OUTER_SPRINT ui_scrollbar ~CGSCRL1~
  OUTER_SPRINT ui_vars_area_list ~cheatAreas~
  OUTER_SPRINT ui_vars_area_strref ~true~
END ELSE BEGIN
  // Should never happen
  FAIL @500  // Enhanced Edition game patched to v2.0 or higher required.
END

// Final adjustments
ACTION_IF (INSTALLED_EET_GUI_SOD) BEGIN
  // EET alternative GUI
  OUTER_SPRINT ui_mode ~sod~
END ELSE ACTION_IF (INSTALLED_DRAGONSPEAR_UI) BEGIN
  // Dragonspear UI++
  OUTER_SPRINT ui_mode ~sod~
END ELSE ACTION_IF (INSTALLED_INFINITY_UI) BEGIN
  // Infinity UI++
  OUTER_SPRINT ui_mode ~iui~
  OUTER_SPRINT ui_scrollbar ~rgdscrl1~
END ELSE ACTION_IF (INSTALLED_LEUI) BEGIN
  // lefreut's Enhanced UI
  OUTER_SPRINT ui_mode ~leui~
END ELSE ACTION_IF (INSTALLED_TIPUN_UI) BEGIN
  // Tipun's User Interface for Enhanced Edition Games
  OUTER_SPRINT ui_mode ~tgui-%game%~
END ELSE ACTION_IF (INSTALLED_IWDEE_UI_BGEE) BEGIN
  // IWDEE-UI-BGEE
  OUTER_SPRINT ui_mode ~iwdee~
END ELSE ACTION_IF (INSTALLED_CBGUI) BEGIN
  // Classic BG UI (non-WeiDU mod)
  OUTER_SPRINT ui_mode ~cbgui~
END


// Preparing lua functions and tables
COPY ~%MOD_FOLDER%/lua/M_a7rhgo.lua~ ~override~
  // Resolving tra references
  REPLACE_EVALUATE ~@\([0-9]+\)~ BEGIN
    PATCH_IF (IS_AN_INT ~MATCH1~) BEGIN
      SPRINT msg (AT "MATCH1")
      SPRINT msg ~"%msg%"~
    END ELSE BEGIN
      SPRINT msg ~""~
      PATCH_WARN ~Not a valid tra reference: %MATCH0%~
    END
  END ~%msg%~
